language: bash
services: docker

env:
  - VERSION=1.5
  - VERSION=1.6
  - VERSION=1.7
  - VERSION=nightly

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="prestashop/docker-internal-images:${VERSION}"
  - image="${image//'/'/-}"

script:
  - docker build --build-arg INSTALL_LANGUAGES=0 -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - docker run -tid --name prestashop $image && docker exec -ti prestashop cat /var/www/html/config/settings.inc.php

after_script:
  - docker images
